"""rename address

Revision ID: 52098b24ea41
Revises: 8888793bba30
Create Date: 2025-06-11 19:35:01.712880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52098b24ea41'
down_revision = '8888793bba30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
